organization:
  label: "TRMNL"
  uri: "https://usetrmnl.com"
profile:
  uri: "https://github.com/%<id>s"
project:
  name: "terminus"
  owner: "usetrmnl"
  uri:
    icon: "%<organization_uri>s/favicon.ico"
    logo: "http://trmnl-oss.s3-website.us-east-2.amazonaws.com/byos/terminus/logo.png"
syndication:
  categories:
    - label: "Milestones"
      name: "milestones"
  entry:
    label: "%<id>s"
    uri: "%<project_uri_version>s"
  id: "%<project_uri_version>s/%<id>s"
  label: "%<organization_label>s: %<project_label>s"
  links:
    - label: "%<organization_label>s: %<project_label>s (web)"
      mime: "text/html"
      relation: "alternate"
      uri: "%<project_uri_home>s/versions"
    - label: "%<organization_label>s: %<project_label>s (feed)"
      mime: "application/atom+xml"
      relation: "self"
      uri: "%<project_uri_home>s/versions.xml"
